{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "task = 'connectivity'\n",
    "filename = task+'_result_gpt4.json'\n",
    "with open(filename, 'r', encoding='utf-8') as f:\n",
    "    datas=json.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "filename1 = task+'_test.json'\n",
    "with open(filename1, 'r', encoding='utf-8') as f:\n",
    "    gt=json.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1861\n",
      "1861\n",
      "{'input_prompt': 'Determine if there is a path between two nodes in the graph. Note that (i,j) means that node i and node j are connected with an undirected edge.\\nGraph: (0,12) (0,13) (0,2) (0,14) (0,23) (0,8) (0,1) (0,25) (0,27) (0,10) (1,29) (1,13) (1,19) (1,28) (1,23) (1,30) (1,25) (1,24) (2,12) (2,5) (2,14) (2,17) (2,23) (3,7) (3,12) (3,19) (3,23) (3,8) (3,30) (3,25) (3,24) (4,33) (5,20) (5,23) (5,30) (6,15) (6,11) (7,32) (7,17) (7,23) (7,8) (7,10) (8,29) (8,12) (8,32) (8,20) (8,19) (8,17) (8,30) (9,29) (9,28) (9,30) (9,24) (10,13) (10,20) (10,14) (10,22) (11,31) (12,13) (12,23) (12,27) (12,26) (13,29) (13,32) (13,14) (13,28) (13,30) (13,24) (14,17) (14,30) (14,22) (14,27) (15,16) (15,31) (15,33) (17,32) (17,20) (17,19) (17,27) (17,24) (17,26) (18,21) (20,28) (20,30) (20,25) (21,31) (22,32) (22,28) (22,30) (23,28) (23,25) (23,27) (24,29) (24,28) (24,26) (25,32) (26,29) (26,27) (27,32) (27,30) (28,32) (28,30)\\nQ: Is there a path between node 14 and node 2?\\nA:', 'answer': 'yes.'}\n"
     ]
    }
   ],
   "source": [
    "print(len(datas))\n",
    "print(len(gt))\n",
    "print(gt[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "import io\n",
    "import sys\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-1884 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 49\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-1940 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 4\n",
      "Exception in thread Thread-1952 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 50, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 9\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n",
      "10\n",
      "11\n",
      "12\n",
      "13\n",
      "14\n",
      "15\n",
      "16\n",
      "17\n",
      "18\n",
      "19\n",
      " no.\n",
      "20\n",
      "21\n",
      "22\n",
      "23\n",
      "24\n",
      "25\n",
      "26\n",
      "27\n",
      "28\n",
      "29\n",
      "30\n",
      "31\n",
      "32\n",
      "33\n",
      "34\n",
      "35\n",
      "36\n",
      "37\n",
      "38\n",
      "39\n",
      "40\n",
      "41\n",
      "No no.\n",
      "42\n",
      "No no.\n",
      "43\n",
      "44\n",
      "45\n",
      "46\n",
      "47\n",
      "48\n",
      "49\n",
      "50\n",
      "51\n",
      "52\n",
      "53\n",
      "54\n",
      "55\n",
      "56\n",
      "57\n",
      "58\n",
      "59\n",
      "Yes yes.\n",
      "60\n",
      "61\n",
      "62\n",
      "63\n",
      "64\n",
      "65\n",
      "66\n",
      "67\n",
      "68\n",
      "69\n",
      "70\n",
      "71\n",
      "72\n",
      "73\n",
      "74\n",
      "75\n",
      " no.\n",
      "76\n",
      "77\n",
      "78\n",
      "79\n",
      "80\n",
      "81\n",
      "82\n",
      "83\n",
      "84\n",
      "85\n",
      "86\n",
      "87\n",
      " no.\n",
      "88\n",
      "89\n",
      "90\n",
      "91\n",
      "92\n",
      "93\n",
      "No no.\n",
      "94\n",
      "95\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-1964 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 37, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 6\n",
      "Exception in thread Thread-1969 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32\n",
      "    When you run this code, it will print `True`, indicating that there is a path between node 10 and node 3.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2007 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 42\n",
      "    This code will output `True`, indicating that there is a path between node 8 and node 7.\n",
      "         ^^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2010 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "96\n",
      "97\n",
      "98\n",
      "99\n",
      " no.\n",
      "100\n",
      "101\n",
      "102\n",
      "103\n",
      "104\n",
      " yes.\n",
      "105\n",
      "106\n",
      "107\n",
      "108\n",
      "109\n",
      "110\n",
      "111\n",
      "112\n",
      "113\n",
      "114\n",
      "115\n",
      "116\n",
      "117\n",
      "118\n",
      "119\n",
      "120\n",
      "121\n",
      "No no.\n",
      "122\n",
      "123\n",
      "124\n",
      "125\n",
      "126\n",
      "127\n",
      "128\n",
      "129\n",
      "130\n",
      "131\n",
      "No no.\n",
      "132\n",
      "133\n",
      "134\n",
      "135\n",
      "136\n",
      "137\n",
      "138\n",
      "139\n",
      "140\n",
      "141\n",
      "142\n",
      " yes.\n",
      "143\n",
      "144\n",
      "145\n",
      " no.\n",
      "146\n",
      "147\n",
      "148\n",
      "149\n",
      "150\n",
      "151\n",
      "152\n",
      "153\n",
      "154\n",
      "155\n",
      "156\n",
      "157\n",
      "158\n",
      "159\n",
      "160\n",
      "No no.\n",
      "161\n",
      "162\n",
      "163\n",
      "164\n",
      "165\n",
      "166\n",
      "167\n",
      "168\n",
      "169\n",
      "No no.\n",
      "170\n",
      "171\n",
      "172\n",
      "173\n",
      "174\n",
      "175\n",
      "176\n",
      "177\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2057 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 41\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2058 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 14\n",
      "Exception in thread Thread-2097 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28\n",
      "    ```plaintext\n",
      "    ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2098 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 40\n",
      "    Running this code will determine if there is a path between node 6 and node 3 in the given graph.\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "SyntaxError: expected 'else' after 'if' expression\n",
      "Exception in thread Thread-2099 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 11\n",
      "Exception in thread Thread-2112 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31\n",
      "    Running this code will print `True`, indicating that there is a path between node 2 and node 8.\n",
      "            ^^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2116 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 36, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 9\n",
      "Exception in thread Thread-2117 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 36\n",
      "    When you run this code, it will print `True`, indicating that there is a path between node 3 and node 2.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "178\n",
      "179\n",
      "180\n",
      "181\n",
      "182\n",
      "183\n",
      "184\n",
      "185\n",
      "186\n",
      "187\n",
      "188\n",
      "189\n",
      "190\n",
      "191\n",
      "192\n",
      " yes.\n",
      "193\n",
      " no.\n",
      "194\n",
      "195\n",
      "196\n",
      "197\n",
      "198\n",
      "199\n",
      "200\n",
      "201\n",
      "202\n",
      "203\n",
      "Yes yes.\n",
      "204\n",
      "205\n",
      "206\n",
      "207\n",
      "208\n",
      "209\n",
      "210\n",
      "211\n",
      "212\n",
      "213\n",
      "214\n",
      "215\n",
      "216\n",
      "217\n",
      "218\n",
      "219\n",
      "220\n",
      "221\n",
      "222\n",
      "223\n",
      "224\n",
      "225\n",
      "226\n",
      "227\n",
      "228\n",
      "229\n",
      "230\n",
      "231\n",
      "232\n",
      " yes.\n",
      "233\n",
      " yes.\n",
      "234\n",
      " no.\n",
      "235\n",
      "236\n",
      "237\n",
      "238\n",
      "239\n",
      "240\n",
      "241\n",
      "242\n",
      "243\n",
      "244\n",
      "245\n",
      "246\n",
      "247\n",
      " yes.\n",
      "248\n",
      "249\n",
      "250\n",
      "251\n",
      " no.\n",
      "252\n",
      " yes.\n",
      "253\n",
      "254\n",
      "255\n",
      "256\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2124 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25\n",
      "    ```plaintext\n",
      "    ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2129 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 41, in <module>\n",
      "  File \"<string>\", line 11, in is_path\n",
      "KeyError: 4\n",
      "Exception in thread Thread-2133 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 29, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n",
      "Exception in thread Thread-2146 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32\n",
      "    When you run this code, it will print `True`, indicating that there is a path between node 1 and node 5.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2147 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 26\n",
      "    Running the above code will print:\n",
      "            ^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2185 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 49\n",
      "    This code will print `True`, indicating that there is a path between node 14 and node 11.\n",
      "         ^^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "257\n",
      "258\n",
      "259\n",
      " no.\n",
      "260\n",
      "261\n",
      "262\n",
      "263\n",
      "264\n",
      " no.\n",
      "265\n",
      "266\n",
      "267\n",
      "268\n",
      " no.\n",
      "269\n",
      "270\n",
      "271\n",
      "272\n",
      "273\n",
      "274\n",
      "275\n",
      "276\n",
      "277\n",
      "278\n",
      "279\n",
      "280\n",
      "281\n",
      " yes.\n",
      "282\n",
      " yes.\n",
      "283\n",
      "284\n",
      "285\n",
      "286\n",
      "287\n",
      "288\n",
      "289\n",
      "290\n",
      "291\n",
      "292\n",
      "293\n",
      "294\n",
      "295\n",
      "296\n",
      "297\n",
      "298\n",
      "299\n",
      "300\n",
      "301\n",
      "302\n",
      "303\n",
      "304\n",
      "305\n",
      "306\n",
      "307\n",
      "308\n",
      "309\n",
      "310\n",
      "311\n",
      "312\n",
      "313\n",
      "314\n",
      "315\n",
      "316\n",
      "317\n",
      "318\n",
      "319\n",
      "320\n",
      " yes.\n",
      "321\n",
      "322\n",
      "323\n",
      "324\n",
      "No no.\n",
      "325\n",
      "326\n",
      "327\n",
      "328\n",
      "329\n",
      "330\n",
      "331\n",
      "332\n",
      "333\n",
      "334\n",
      "Yes yes.\n",
      "335\n",
      "336\n",
      "337\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2229 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 41\n",
      "    When you run this code, it will print `True` if there is a path between node 10 and node 3, and `False` otherwise.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2234 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31\n",
      "    Running this code will print the result of whether there is a path between node 2 and node 3.\n",
      "                           ^^^^^^^^^\n",
      "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?\n",
      "Exception in thread Thread-2237 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 0\n",
      "Exception in thread Thread-2245 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 4\n",
      "Exception in thread Thread-2249 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 30\n",
      "    When you run this code, it will print `False`, indicating there is no path between node 8 and node 10.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "338\n",
      "339\n",
      "340\n",
      "341\n",
      "342\n",
      "343\n",
      "344\n",
      "345\n",
      "346\n",
      "347\n",
      "348\n",
      "349\n",
      "350\n",
      "351\n",
      "352\n",
      "353\n",
      "354\n",
      "355\n",
      "356\n",
      "357\n",
      "358\n",
      "359\n",
      "360\n",
      "361\n",
      "362\n",
      "363\n",
      "364\n",
      " no.\n",
      "365\n",
      "366\n",
      "367\n",
      "368\n",
      "369\n",
      " yes.\n",
      "370\n",
      "371\n",
      "372\n",
      " no.\n",
      "373\n",
      "374\n",
      "375\n",
      "376\n",
      "377\n",
      "378\n",
      "379\n",
      "380\n",
      " no.\n",
      "381\n",
      "382\n",
      "383\n",
      "384\n",
      " no.\n",
      "385\n",
      "386\n",
      "387\n",
      "388\n",
      "389\n",
      "390\n",
      "391\n",
      "392\n",
      "393\n",
      "394\n",
      "395\n",
      "396\n",
      "397\n",
      "398\n",
      "399\n",
      "400\n",
      "401\n",
      "402\n",
      "Yes yes.\n",
      "403\n",
      "404\n",
      "405\n",
      "406\n",
      "407\n",
      "408\n",
      "409\n",
      "410\n",
      "411\n",
      "412\n",
      "413\n",
      "414\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2282 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 26\n",
      "Exception in thread Thread-2299 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 50, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 1\n",
      "Exception in thread Thread-2326 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n",
      "Exception in thread Thread-2355 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "415\n",
      "416\n",
      "417\n",
      " no.\n",
      "418\n",
      "419\n",
      "420\n",
      "421\n",
      "422\n",
      "423\n",
      "424\n",
      "425\n",
      "426\n",
      "427\n",
      "428\n",
      "429\n",
      "430\n",
      "431\n",
      "Yes yes.\n",
      "432\n",
      "433\n",
      "434\n",
      " no.\n",
      "435\n",
      "436\n",
      "437\n",
      "438\n",
      "No no.\n",
      "439\n",
      "440\n",
      "441\n",
      "442\n",
      "443\n",
      "444\n",
      "445\n",
      "446\n",
      "447\n",
      "448\n",
      "449\n",
      "Yes yes.\n",
      "450\n",
      "No no.\n",
      "451\n",
      "452\n",
      "453\n",
      "454\n",
      "455\n",
      "456\n",
      "457\n",
      "458\n",
      "459\n",
      "460\n",
      "461\n",
      " no.\n",
      "462\n",
      "463\n",
      "464\n",
      "465\n",
      "466\n",
      "467\n",
      "468\n",
      "469\n",
      "470\n",
      "471\n",
      "472\n",
      "473\n",
      "474\n",
      "Yes yes.\n",
      "475\n",
      "476\n",
      "477\n",
      "478\n",
      "479\n",
      "480\n",
      "Yes yes.\n",
      "481\n",
      "482\n",
      "483\n",
      "484\n",
      "485\n",
      "486\n",
      "487\n",
      "488\n",
      "489\n",
      "490\n",
      " no.\n",
      "491\n",
      "492\n",
      "493\n",
      "494\n",
      "No no.\n",
      "495\n",
      "496\n",
      "497\n",
      "498\n",
      "No no.\n",
      "499\n",
      "500\n",
      "501\n",
      "502\n",
      "Yes yes.\n",
      "503\n",
      "504\n",
      "505\n",
      "506\n",
      "507\n",
      "508\n",
      "509\n",
      "510\n",
      "511\n",
      "512\n",
      "513\n",
      "514\n",
      "515\n",
      "516\n",
      "517\n",
      "518\n",
      "519\n",
      "No no.\n",
      "520\n",
      "521\n",
      "522\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2416 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 49\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2423 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31\n",
      "    When you run this code, it will print `No` because there is no path between node 7 and node 5 in the given graph.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "523\n",
      "524\n",
      "525\n",
      "526\n",
      "527\n",
      "528\n",
      "529\n",
      "Yes yes.\n",
      "530\n",
      "531\n",
      "532\n",
      "533\n",
      "534\n",
      "535\n",
      "536\n",
      "537\n",
      "538\n",
      "539\n",
      "540\n",
      "541\n",
      "542\n",
      "543\n",
      "544\n",
      "545\n",
      "546\n",
      "547\n",
      "548\n",
      "549\n",
      "550\n",
      "551\n",
      " no.\n",
      "552\n",
      "553\n",
      "554\n",
      "555\n",
      "556\n",
      "557\n",
      "558\n",
      " no.\n",
      "559\n",
      "560\n",
      "561\n",
      "562\n",
      "563\n",
      "564\n",
      "565\n",
      "566\n",
      "567\n",
      "568\n",
      "569\n",
      "570\n",
      "571\n",
      "572\n",
      "573\n",
      "574\n",
      "575\n",
      "576\n",
      "577\n",
      "578\n",
      "579\n",
      "580\n",
      "581\n",
      "582\n",
      "583\n",
      "584\n",
      "585\n",
      "586\n",
      "587\n",
      "588\n",
      "589\n",
      "Yes yes.\n",
      "590\n",
      "591\n",
      "592\n",
      "593\n",
      "594\n",
      "595\n",
      "596\n",
      "597\n",
      "598\n",
      "599\n",
      "600\n",
      "601\n",
      "No no.\n",
      "602\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2467 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 11\n",
      "Exception in thread Thread-2508 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 45, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 13\n",
      "Exception in thread Thread-2516 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 11\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " no.\n",
      "603\n",
      "604\n",
      "605\n",
      "606\n",
      "607\n",
      "608\n",
      "609\n",
      "610\n",
      "611\n",
      "612\n",
      "613\n",
      "614\n",
      "615\n",
      "616\n",
      "617\n",
      "618\n",
      "619\n",
      "620\n",
      "Yes yes.\n",
      "621\n",
      "622\n",
      "623\n",
      "624\n",
      "625\n",
      "626\n",
      "627\n",
      "No no.\n",
      "628\n",
      "629\n",
      "630\n",
      "No no.\n",
      "631\n",
      "632\n",
      "633\n",
      "No no.\n",
      "634\n",
      "635\n",
      "636\n",
      "637\n",
      "Yes yes.\n",
      "638\n",
      "639\n",
      "640\n",
      "641\n",
      "642\n",
      "643\n",
      " no.\n",
      "644\n",
      "645\n",
      "646\n",
      "647\n",
      "648\n",
      "649\n",
      "650\n",
      "651\n",
      " no.\n",
      "652\n",
      "653\n",
      "654\n",
      "655\n",
      "656\n",
      "657\n",
      "658\n",
      "659\n",
      "660\n",
      "661\n",
      "662\n",
      "663\n",
      "Yes yes.\n",
      "664\n",
      "665\n",
      "666\n",
      "667\n",
      "668\n",
      "669\n",
      "670\n",
      "671\n",
      "672\n",
      "673\n",
      "674\n",
      "675\n",
      "676\n",
      "677\n",
      "678\n",
      "679\n",
      "680\n",
      "681\n",
      "682\n",
      "683\n",
      "684\n",
      "685\n",
      "686\n",
      "687\n",
      "688\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2599 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 35, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 5\n",
      "Exception in thread Thread-2623 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 11\n",
      "Exception in thread Thread-2625 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 42\n",
      "    Running this code will output:\n",
      "            ^^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "689\n",
      "690\n",
      "691\n",
      "692\n",
      "693\n",
      "694\n",
      "695\n",
      "No no.\n",
      "696\n",
      "697\n",
      "698\n",
      "699\n",
      "700\n",
      "701\n",
      "702\n",
      "703\n",
      "No no.\n",
      "704\n",
      "705\n",
      "706\n",
      "707\n",
      "708\n",
      "709\n",
      "710\n",
      "711\n",
      "712\n",
      "713\n",
      "714\n",
      "715\n",
      "716\n",
      "717\n",
      "718\n",
      "719\n",
      "720\n",
      "721\n",
      "722\n",
      "723\n",
      "724\n",
      "725\n",
      "726\n",
      "727\n",
      "728\n",
      "729\n",
      "730\n",
      "No no.\n",
      "731\n",
      "732\n",
      "733\n",
      "734\n",
      " no.\n",
      "735\n",
      "736\n",
      "737\n",
      "738\n",
      "739\n",
      "740\n",
      "741\n",
      "742\n",
      "743\n",
      "744\n",
      "745\n",
      "746\n",
      "747\n",
      "748\n",
      "749\n",
      "750\n",
      "751\n",
      "752\n",
      "753\n",
      "754\n",
      "755\n",
      "756\n",
      "757\n",
      "758\n",
      " no.\n",
      "759\n",
      "760\n",
      " no.\n",
      "761\n",
      "762\n",
      "763\n",
      "No no.\n",
      "764\n",
      "765\n",
      "766\n",
      "767\n",
      "768\n",
      "769\n",
      "770\n",
      "Yes yes.\n",
      "771\n",
      "772\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2639 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 30\n",
      "    When you run this code, it will print \"Yes\" indicating that there is a path between node 7 and node 4.\n",
      "                                    ^^^^^^^^^^^\n",
      "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?\n",
      "Exception in thread Thread-2700 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 22\n",
      "Exception in thread Thread-2713 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 30\n",
      "    When you run this code, it will print `True` if there is a path between node 14 and node 5, otherwise it will print `False`.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "773\n",
      "774\n",
      " yes.\n",
      "775\n",
      "Yes yes.\n",
      "776\n",
      "777\n",
      "778\n",
      "779\n",
      "780\n",
      "781\n",
      "782\n",
      "783\n",
      "Yes yes.\n",
      "784\n",
      "785\n",
      "786\n",
      "787\n",
      "788\n",
      "789\n",
      "790\n",
      "791\n",
      "792\n",
      "793\n",
      "794\n",
      "795\n",
      "No no.\n",
      "796\n",
      "797\n",
      "798\n",
      "799\n",
      "800\n",
      "801\n",
      "802\n",
      "No no.\n",
      "803\n",
      "804\n",
      "805\n",
      "806\n",
      "807\n",
      "808\n",
      "809\n",
      "810\n",
      "811\n",
      "812\n",
      "813\n",
      "814\n",
      "815\n",
      "816\n",
      "No no.\n",
      "817\n",
      "818\n",
      "819\n",
      "820\n",
      "821\n",
      "822\n",
      "823\n",
      "824\n",
      "825\n",
      "826\n",
      "No no.\n",
      "827\n",
      "828\n",
      "829\n",
      "830\n",
      "831\n",
      "832\n",
      "833\n",
      "834\n",
      "835\n",
      " no.\n",
      "836\n",
      "837\n",
      "838\n",
      "839\n",
      "840\n",
      "841\n",
      "842\n",
      "843\n",
      "844\n",
      "845\n",
      "846\n",
      "847\n",
      "848\n",
      " no.\n",
      "849\n",
      "850\n",
      "851\n",
      "852\n",
      "853\n",
      "854\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2744 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 30\n",
      "    Running this code will print `True`, indicating that there is a path between node 11 and node 10.\n",
      "            ^^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-2764 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 35\n",
      "    Running this code will determine if there is a path between node 5 and node 13 in the given graph.\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "SyntaxError: expected 'else' after 'if' expression\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "855\n",
      "856\n",
      "857\n",
      "858\n",
      "859\n",
      "860\n",
      "861\n",
      "862\n",
      "863\n",
      "864\n",
      "865\n",
      "866\n",
      "867\n",
      "868\n",
      "869\n",
      "870\n",
      "871\n",
      "872\n",
      "873\n",
      "874\n",
      "875\n",
      "876\n",
      "No no.\n",
      "877\n",
      "878\n",
      "879\n",
      " no.\n",
      "880\n",
      "881\n",
      "882\n",
      "883\n",
      "884\n",
      "885\n",
      "886\n",
      "887\n",
      "888\n",
      "889\n",
      "890\n",
      "891\n",
      "892\n",
      "893\n",
      "894\n",
      "895\n",
      "896\n",
      "897\n",
      "898\n",
      "899\n",
      " yes.\n",
      "900\n",
      "901\n",
      "902\n",
      "903\n",
      "904\n",
      "905\n",
      "906\n",
      "907\n",
      "908\n",
      "909\n",
      "910\n",
      "911\n",
      "912\n",
      "913\n",
      "914\n",
      "915\n",
      "916\n",
      "917\n",
      "918\n",
      "919\n",
      "920\n",
      "921\n",
      "922\n",
      "923\n",
      "924\n",
      "925\n",
      "No no.\n",
      "926\n",
      "927\n",
      "No no.\n",
      "928\n",
      "929\n",
      "930\n",
      "931\n",
      "932\n",
      "933\n",
      "934\n",
      "935\n",
      "936\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2803 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 4\n",
      "Exception in thread Thread-2818 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 40, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 8\n",
      "Exception in thread Thread-2831 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 42, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 26\n",
      "Exception in thread Thread-2835 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 39, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 6\n",
      "Exception in thread Thread-2845 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 26, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 9\n",
      "Exception in thread Thread-2861 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32\n",
      "    When you run this code, it will print `True`, indicating that there is a path between node 0 and node 4.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "937\n",
      "938\n",
      " no.\n",
      "939\n",
      "940\n",
      "941\n",
      "942\n",
      "943\n",
      "944\n",
      "945\n",
      "946\n",
      "947\n",
      "No no.\n",
      "948\n",
      "949\n",
      "950\n",
      "951\n",
      "952\n",
      "No no.\n",
      "953\n",
      " no.\n",
      "954\n",
      "955\n",
      "956\n",
      "957\n",
      "958\n",
      "959\n",
      "960\n",
      "961\n",
      "962\n",
      "963\n",
      "964\n",
      "965\n",
      "966\n",
      " no.\n",
      "967\n",
      "968\n",
      "969\n",
      "970\n",
      " no.\n",
      "971\n",
      "972\n",
      "973\n",
      "974\n",
      "975\n",
      "976\n",
      "977\n",
      "978\n",
      "979\n",
      "980\n",
      " no.\n",
      "981\n",
      "982\n",
      "983\n",
      "984\n",
      "Yes yes.\n",
      "985\n",
      "986\n",
      "987\n",
      "988\n",
      "989\n",
      "990\n",
      "991\n",
      "992\n",
      "993\n",
      "994\n",
      "995\n",
      "996\n",
      " yes.\n",
      "997\n",
      "998\n",
      "999\n",
      "1000\n",
      "1001\n",
      "1002\n",
      "No no.\n",
      "1003\n",
      "1004\n",
      "1005\n",
      "1006\n",
      "1007\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-2953 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 28\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1008\n",
      "1009\n",
      "1010\n",
      "1011\n",
      "1012\n",
      "1013\n",
      "1014\n",
      "1015\n",
      "1016\n",
      "1017\n",
      "1018\n",
      "1019\n",
      "1020\n",
      "1021\n",
      "1022\n",
      "1023\n",
      "1024\n",
      "1025\n",
      "1026\n",
      "1027\n",
      "1028\n",
      "1029\n",
      "1030\n",
      "1031\n",
      "1032\n",
      "1033\n",
      "1034\n",
      "1035\n",
      "1036\n",
      "1037\n",
      "1038\n",
      "1039\n",
      "1040\n",
      "1041\n",
      "1042\n",
      "1043\n",
      "1044\n",
      "No no.\n",
      "1045\n",
      "1046\n",
      "1047\n",
      "1048\n",
      "1049\n",
      "1050\n",
      "1051\n",
      "1052\n",
      "1053\n",
      "1054\n",
      "1055\n",
      "1056\n",
      "1057\n",
      "No no.\n",
      "1058\n",
      "1059\n",
      "1060\n",
      "1061\n",
      "1062\n",
      "1063\n",
      "1064\n",
      "1065\n",
      "1066\n",
      "1067\n",
      "1068\n",
      "1069\n",
      "1070\n",
      "1071\n",
      "1072\n",
      "1073\n",
      "1074\n",
      "1075\n",
      "1076\n",
      "1077\n",
      "1078\n",
      "1079\n",
      "1080\n",
      "1081\n",
      "1082\n",
      "1083\n",
      "1084\n",
      "1085\n",
      "1086\n",
      "1087\n",
      "1088\n",
      " no.\n",
      "1089\n",
      "1090\n",
      "1091\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3008 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 26, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 10\n",
      "Exception in thread Thread-3026 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 45\n",
      "    ```plaintext\n",
      "    ^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1092\n",
      "1093\n",
      "1094\n",
      "1095\n",
      "1096\n",
      "1097\n",
      "1098\n",
      "1099\n",
      "1100\n",
      "1101\n",
      "1102\n",
      "1103\n",
      "1104\n",
      "1105\n",
      "1106\n",
      "1107\n",
      "1108\n",
      "1109\n",
      "1110\n",
      "1111\n",
      "1112\n",
      "1113\n",
      "1114\n",
      "1115\n",
      "1116\n",
      "1117\n",
      "1118\n",
      "1119\n",
      "1120\n",
      "1121\n",
      "1122\n",
      "1123\n",
      "1124\n",
      "1125\n",
      "1126\n",
      "Yes yes.\n",
      "1127\n",
      "1128\n",
      "No no.\n",
      "1129\n",
      "1130\n",
      "1131\n",
      "1132\n",
      "1133\n",
      "1134\n",
      "1135\n",
      "1136\n",
      "1137\n",
      "1138\n",
      "No no.\n",
      "1139\n",
      "1140\n",
      "1141\n",
      "1142\n",
      "1143\n",
      " no.\n",
      "1144\n",
      "1145\n",
      "1146\n",
      "1147\n",
      "1148\n",
      "1149\n",
      "1150\n",
      "1151\n",
      "1152\n",
      "1153\n",
      "1154\n",
      "1155\n",
      "1156\n",
      "1157\n",
      "1158\n",
      "1159\n",
      "1160\n",
      "1161\n",
      " no.\n",
      "1162\n",
      "1163\n",
      "1164\n",
      "1165\n",
      "1166\n",
      "1167\n",
      "1168\n",
      "1169\n",
      "1170\n",
      "1171\n",
      "1172\n",
      "1173\n",
      "1174\n",
      "No no.\n",
      "1175\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3049 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n",
      "Exception in thread Thread-3070 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n",
      "Exception in thread Thread-3072 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n",
      "Exception in thread Thread-3074 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 17\n",
      "Exception in thread Thread-3079 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 4\n",
      "Exception in thread Thread-3098 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 9\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1176\n",
      "1177\n",
      "1178\n",
      "1179\n",
      "1180\n",
      "1181\n",
      "No no.\n",
      "1182\n",
      "1183\n",
      "1184\n",
      " no.\n",
      "1185\n",
      "Yes yes.\n",
      "1186\n",
      "1187\n",
      "1188\n",
      "1189\n",
      "1190\n",
      "1191\n",
      "1192\n",
      "1193\n",
      "1194\n",
      "1195\n",
      "1196\n",
      "1197\n",
      "No no.\n",
      "1198\n",
      "1199\n",
      "1200\n",
      "1201\n",
      "1202\n",
      "1203\n",
      "1204\n",
      "1205\n",
      " no.\n",
      "1206\n",
      "No no.\n",
      "1207\n",
      " no.\n",
      "1208\n",
      "1209\n",
      " no.\n",
      "1210\n",
      "1211\n",
      "1212\n",
      "1213\n",
      "1214\n",
      " no.\n",
      "1215\n",
      "1216\n",
      "1217\n",
      "1218\n",
      "1219\n",
      "1220\n",
      "No no.\n",
      "1221\n",
      "1222\n",
      "1223\n",
      "1224\n",
      "1225\n",
      "1226\n",
      "1227\n",
      "1228\n",
      "1229\n",
      "1230\n",
      "1231\n",
      "1232\n",
      "1233\n",
      " no.\n",
      "1234\n",
      "1235\n",
      "1236\n",
      "1237\n",
      "1238\n",
      "1239\n",
      "1240\n",
      "1241\n",
      "1242\n",
      "1243\n",
      "No no.\n",
      "1244\n",
      "1245\n",
      "1246\n",
      "1247\n",
      "1248\n",
      "1249\n",
      "1250\n",
      "1251\n",
      "1252\n",
      "1253\n",
      "1254\n",
      "1255\n",
      "1256\n",
      "1257\n",
      "1258\n",
      "1259\n",
      "1260\n",
      "1261\n",
      "1262\n",
      "1263\n",
      "1264\n",
      "1265\n",
      "1266\n",
      "No no.\n",
      "1267\n",
      "1268\n",
      "1269\n",
      "1270\n",
      "1271\n",
      "1272\n",
      "1273\n",
      "1274\n",
      "1275\n",
      "1276\n",
      "1277\n",
      "1278\n",
      "1279\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3145 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 30\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3166 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 21\n",
      "Exception in thread Thread-3197 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 24, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 3\n",
      "Exception in thread Thread-3208 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 6\n",
      "Exception in thread Thread-3209 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 22\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1280\n",
      " yes.\n",
      "1281\n",
      "1282\n",
      "1283\n",
      "1284\n",
      "1285\n",
      "1286\n",
      "1287\n",
      "1288\n",
      "1289\n",
      "1290\n",
      "1291\n",
      "1292\n",
      "1293\n",
      "1294\n",
      "1295\n",
      "1296\n",
      "1297\n",
      "1298\n",
      "1299\n",
      "1300\n",
      "1301\n",
      " no.\n",
      "1302\n",
      "1303\n",
      "1304\n",
      "1305\n",
      "1306\n",
      "1307\n",
      "1308\n",
      "1309\n",
      "1310\n",
      "1311\n",
      "1312\n",
      "1313\n",
      "1314\n",
      "1315\n",
      "1316\n",
      "1317\n",
      "1318\n",
      "1319\n",
      "1320\n",
      "1321\n",
      "1322\n",
      "1323\n",
      "1324\n",
      "1325\n",
      "1326\n",
      "1327\n",
      "1328\n",
      "1329\n",
      "1330\n",
      "1331\n",
      "1332\n",
      " no.\n",
      "1333\n",
      "1334\n",
      "1335\n",
      "1336\n",
      "1337\n",
      "1338\n",
      "1339\n",
      "1340\n",
      "1341\n",
      "1342\n",
      "1343\n",
      " no.\n",
      "1344\n",
      " no.\n",
      "1345\n",
      "1346\n",
      "1347\n",
      "1348\n",
      "1349\n",
      "1350\n",
      "1351\n",
      "1352\n",
      "1353\n",
      "1354\n",
      "1355\n",
      "1356\n",
      "1357\n",
      "1358\n",
      "1359\n",
      "Yes yes.\n",
      "1360\n",
      "1361\n",
      "1362\n",
      "1363\n",
      "1364\n",
      "1365\n",
      "1366\n",
      "1367\n",
      "1368\n",
      "1369\n",
      "1370\n",
      "1371\n",
      "1372\n",
      "1373\n",
      "1374\n",
      "1375\n",
      "1376\n",
      "1377\n",
      "1378\n",
      "1379\n",
      "No no.\n",
      "1380\n",
      "1381\n",
      "1382\n",
      "1383\n",
      "1384\n",
      "1385\n",
      "1386\n",
      "1387\n",
      "1388\n",
      "1389\n",
      "1390\n",
      "1391\n",
      "1392\n",
      "1393\n",
      "1394\n",
      "1395\n",
      "1396\n",
      "1397\n",
      "1398\n",
      "1399\n",
      "1400\n",
      "1401\n",
      "1402\n",
      "1403\n",
      "1404\n",
      "1405\n",
      "1406\n",
      "1407\n",
      "1408\n",
      "1409\n",
      "1410\n",
      "1411\n",
      "No no.\n",
      "1412\n",
      "1413\n",
      "1414\n",
      "1415\n",
      "1416\n",
      "1417\n",
      "1418\n",
      "1419\n",
      "1420\n",
      "Yes yes.\n",
      "1421\n",
      "1422\n",
      "1423\n",
      "1424\n",
      "1425\n",
      "1426\n",
      "1427\n",
      "1428\n",
      "1429\n",
      "1430\n",
      "1431\n",
      "1432\n",
      "1433\n",
      "Yes yes.\n",
      "1434\n",
      "1435\n",
      "1436\n",
      "1437\n",
      "1438\n",
      "1439\n",
      "1440\n",
      "1441\n",
      "1442\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3308 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 27\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3327 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 13\n",
      "Exception in thread Thread-3367 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 44\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3376 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 28, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 13\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1443\n",
      " no.\n",
      "1444\n",
      "1445\n",
      "1446\n",
      "1447\n",
      "1448\n",
      "1449\n",
      "1450\n",
      "1451\n",
      "1452\n",
      "1453\n",
      "1454\n",
      "1455\n",
      "1456\n",
      "1457\n",
      "1458\n",
      "1459\n",
      "1460\n",
      "1461\n",
      "1462\n",
      " no.\n",
      "1463\n",
      "1464\n",
      "1465\n",
      "1466\n",
      "1467\n",
      "Yes yes.\n",
      "1468\n",
      "1469\n",
      "1470\n",
      "1471\n",
      "1472\n",
      "1473\n",
      "1474\n",
      "1475\n",
      "No no.\n",
      "1476\n",
      "1477\n",
      "1478\n",
      "1479\n",
      "1480\n",
      "1481\n",
      "1482\n",
      "1483\n",
      "1484\n",
      "No no.\n",
      "1485\n",
      "1486\n",
      "1487\n",
      "1488\n",
      "1489\n",
      "1490\n",
      "1491\n",
      "1492\n",
      "1493\n",
      "1494\n",
      "1495\n",
      "1496\n",
      "1497\n",
      "1498\n",
      "1499\n",
      "1500\n",
      "1501\n",
      "1502\n",
      " no.\n",
      "1503\n",
      "1504\n",
      "1505\n",
      "1506\n",
      "1507\n",
      "1508\n",
      "1509\n",
      "1510\n",
      "1511\n",
      " no.\n",
      "1512\n",
      "1513\n",
      "1514\n",
      "1515\n",
      "1516\n",
      "1517\n",
      "1518\n",
      "1519\n",
      "1520\n",
      "No no.\n",
      "1521\n",
      "1522\n",
      "1523\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3388 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 26, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 17\n",
      "Exception in thread Thread-3414 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32\n",
      "    When you run this code, it will print `False`, indicating that there is no path between node 0 and node 10.\n",
      "         ^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3420 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 30, in <module>\n",
      "  File \"<string>\", line 11, in is_path\n",
      "KeyError: 7\n",
      "Exception in thread Thread-3434 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31\n",
      "    Running this code will print `True`, indicating that there is a path between node 2 and node 5.\n",
      "            ^^^^\n",
      "SyntaxError: invalid syntax\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " no.\n",
      "1524\n",
      "1525\n",
      "1526\n",
      "No no.\n",
      "1527\n",
      "1528\n",
      "1529\n",
      "1530\n",
      "1531\n",
      "1532\n",
      "1533\n",
      "1534\n",
      "1535\n",
      "1536\n",
      "1537\n",
      "1538\n",
      "Yes yes.\n",
      "1539\n",
      "1540\n",
      "1541\n",
      "1542\n",
      "1543\n",
      "1544\n",
      "1545\n",
      "1546\n",
      "1547\n",
      "1548\n",
      "1549\n",
      " no.\n",
      "1550\n",
      "1551\n",
      "1552\n",
      "1553\n",
      "1554\n",
      "1555\n",
      " no.\n",
      "1556\n",
      "1557\n",
      "1558\n",
      "1559\n",
      "1560\n",
      "1561\n",
      "1562\n",
      "1563\n",
      "1564\n",
      "1565\n",
      "1566\n",
      "1567\n",
      "1568\n",
      "1569\n",
      " yes.\n",
      "1570\n",
      "1571\n",
      "1572\n",
      "1573\n",
      "1574\n",
      "Yes yes.\n",
      "1575\n",
      "1576\n",
      "1577\n",
      "1578\n",
      "1579\n",
      "1580\n",
      "1581\n",
      "1582\n",
      "1583\n",
      "1584\n",
      "1585\n",
      "1586\n",
      "1587\n",
      "1588\n",
      "1589\n",
      "1590\n",
      "1591\n",
      "1592\n",
      "1593\n",
      "Yes yes.\n",
      "1594\n",
      "1595\n",
      "1596\n",
      "1597\n",
      "1598\n",
      "Yes yes.\n",
      "1599\n",
      "1600\n",
      "1601\n",
      "1602\n",
      "No no.\n",
      "1603\n",
      "1604\n",
      "1605\n",
      "1606\n",
      "1607\n",
      "1608\n",
      "1609\n",
      "1610\n",
      "1611\n",
      "1612\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3487 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 34, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 1\n",
      "Exception in thread Thread-3520 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 35, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 4\n",
      "Exception in thread Thread-3537 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 42\n",
      "    This code will print `True`, indicating that there is a path between node 5 and node 1.\n",
      "         ^^^^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3544 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 26, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 10\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1613\n",
      "1614\n",
      "1615\n",
      "1616\n",
      "1617\n",
      "1618\n",
      "1619\n",
      "1620\n",
      "1621\n",
      "1622\n",
      " no.\n",
      "1623\n",
      "1624\n",
      "1625\n",
      "1626\n",
      "1627\n",
      "1628\n",
      "1629\n",
      "1630\n",
      "1631\n",
      "1632\n",
      "1633\n",
      "1634\n",
      "1635\n",
      "1636\n",
      "1637\n",
      "1638\n",
      "1639\n",
      "1640\n",
      "1641\n",
      "1642\n",
      "1643\n",
      "1644\n",
      "1645\n",
      "1646\n",
      "1647\n",
      "1648\n",
      "1649\n",
      "1650\n",
      "1651\n",
      "1652\n",
      "1653\n",
      "1654\n",
      "1655\n",
      " no.\n",
      "1656\n",
      "1657\n",
      "1658\n",
      "1659\n",
      "1660\n",
      "1661\n",
      "1662\n",
      "1663\n",
      "1664\n",
      "1665\n",
      "1666\n",
      "1667\n",
      "1668\n",
      "1669\n",
      "1670\n",
      "1671\n",
      "1672\n",
      " yes.\n",
      "1673\n",
      "1674\n",
      "1675\n",
      "1676\n",
      "1677\n",
      "1678\n",
      "1679\n",
      " no.\n",
      "1680\n",
      "1681\n",
      "1682\n",
      "1683\n",
      "1684\n",
      "1685\n",
      "1686\n",
      "1687\n",
      "1688\n",
      "1689\n",
      "1690\n",
      "1691\n",
      "1692\n",
      "1693\n",
      "1694\n",
      "1695\n",
      "1696\n",
      "1697\n",
      "1698\n",
      "1699\n",
      "1700\n",
      "1701\n",
      "1702\n",
      "1703\n",
      "1704\n",
      "1705\n",
      "1706\n",
      "1707\n",
      "Yes yes.\n",
      "1708\n",
      "1709\n",
      "1710\n",
      "1711\n",
      "1712\n",
      "1713\n",
      "1714\n",
      "1715\n",
      "1716\n",
      "1717\n",
      "1718\n",
      "1719\n",
      "1720\n",
      "1721\n",
      "1722\n",
      "1723\n",
      "1724\n",
      "1725\n",
      "1726\n",
      "1727\n",
      "1728\n",
      "1729\n",
      "1730\n",
      "No no.\n",
      "1731\n",
      "1732\n",
      "1733\n",
      "1734\n",
      "1735\n",
      "1736\n",
      "1737\n",
      "1738\n",
      "1739\n",
      "1740\n",
      "1741\n",
      "1742\n",
      "1743\n",
      "1744\n",
      "1745\n",
      "1746\n",
      "1747\n",
      "1748\n",
      "1749\n",
      "1750\n",
      "1751\n",
      "1752\n",
      "1753\n",
      "Yes yes.\n",
      "1754\n",
      "1755\n",
      "1756\n",
      "1757\n",
      "1758\n",
      "1759\n",
      "1760\n",
      "1761\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3626 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 11\n",
      "Exception in thread Thread-3631 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 31, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 4\n",
      "Exception in thread Thread-3634 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32\n",
      "    ```plaintext\n",
      "    ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3678 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 33\n",
      "    Output:\n",
      "           ^\n",
      "SyntaxError: invalid syntax\n",
      "Exception in thread Thread-3699 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 25, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 2\n",
      "Exception in thread Thread-3718 (target):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/home/qifanzhang/anaconda3/lib/python3.12/threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/tmp/ipykernel_2336063/4073402840.py\", line 12, in target\n",
      "  File \"<string>\", line 32, in <module>\n",
      "  File \"<string>\", line 5, in dfs\n",
      "KeyError: 17\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " no.\n",
      "1762\n",
      "1763\n",
      "1764\n",
      "1765\n",
      "1766\n",
      " no.\n",
      "1767\n",
      "1768\n",
      "1769\n",
      " no.\n",
      "1770\n",
      "1771\n",
      "1772\n",
      "1773\n",
      "1774\n",
      "1775\n",
      "1776\n",
      "1777\n",
      "1778\n",
      "1779\n",
      "1780\n",
      "1781\n",
      "1782\n",
      "1783\n",
      "1784\n",
      "1785\n",
      "1786\n",
      "1787\n",
      "1788\n",
      "1789\n",
      "1790\n",
      "1791\n",
      "1792\n",
      "1793\n",
      "1794\n",
      "No no.\n",
      "1795\n",
      "1796\n",
      "1797\n",
      "1798\n",
      "1799\n",
      "1800\n",
      "1801\n",
      "1802\n",
      "1803\n",
      "1804\n",
      "1805\n",
      "1806\n",
      "1807\n",
      "1808\n",
      "1809\n",
      "1810\n",
      "1811\n",
      "1812\n",
      "1813\n",
      " no.\n",
      "1814\n",
      "1815\n",
      "1816\n",
      "1817\n",
      "1818\n",
      "1819\n",
      "1820\n",
      "1821\n",
      "1822\n",
      "1823\n",
      "1824\n",
      "1825\n",
      "1826\n",
      "1827\n",
      "1828\n",
      "1829\n",
      "1830\n",
      "1831\n",
      "1832\n",
      "1833\n",
      "1834\n",
      " no.\n",
      "1835\n",
      "1836\n",
      "Yes yes.\n",
      "1837\n",
      "1838\n",
      "1839\n",
      "1840\n",
      "1841\n",
      "1842\n",
      "No no.\n",
      "1843\n",
      "1844\n",
      "1845\n",
      "1846\n",
      "1847\n",
      "1848\n",
      "1849\n",
      "1850\n",
      "1851\n",
      "1852\n",
      "1853\n",
      " no.\n",
      "1854\n",
      "No no.\n",
      "1855\n",
      "1856\n",
      "1857\n",
      "1858\n",
      "1859\n",
      "1860\n"
     ]
    }
   ],
   "source": [
    "error_cnt = 0\n",
    "correct_cnt = 0\n",
    "import threading\n",
    "import re\n",
    "\n",
    "class TimeoutException(Exception):\n",
    "    pass\n",
    "\n",
    "def run_with_timeout(code, timeout=15):\n",
    "    # 定义执行代码的函数\n",
    "    def target():\n",
    "        exec(code, globals(), globals())\n",
    "\n",
    "    thread = threading.Thread(target=target)\n",
    "    thread.start()\n",
    "    thread.join(timeout)\n",
    "\n",
    "    if thread.is_alive():\n",
    "        raise TimeoutException(\"Code execution exceeded timeout limit.\")\n",
    "\n",
    "for i, (key,value) in enumerate(datas.items()):\n",
    "    print(i)\n",
    "    text = value['gpt4']\n",
    "    code = re.sub(r'^```python\\n|```$', '', text, flags=re.MULTILINE)\n",
    "    ans = gt[i]['answer']\n",
    "\n",
    "    # 创建一个 StringIO 对象来捕获输出\n",
    "    output = io.StringIO()\n",
    "\n",
    "    # 重定向 sys.stdout\n",
    "    old_stdout = sys.stdout\n",
    "    sys.stdout = output\n",
    "\n",
    "    try:\n",
    "        run_with_timeout(code,timeout=5)\n",
    "    except TimeoutException as e:\n",
    "        error_cnt = error_cnt + 1\n",
    "        print(e)\n",
    "        continue\n",
    "    except:\n",
    "        sys.stdout = old_stdout\n",
    "        print(code)\n",
    "        error_cnt = error_cnt + 1\n",
    "        continue\n",
    "    finally:\n",
    "        sys.stdout = old_stdout\n",
    "    \n",
    "\n",
    "    # 获取输出内容\n",
    "    output_content = output.getvalue()\n",
    "    output_content = str(output_content).strip()\n",
    "    # print(\"Captured Output:\")\n",
    "    \n",
    "    if output_content == 'True':\n",
    "        output_content = 'yes'\n",
    "    elif output_content == 'False':                                 \n",
    "        output_content = 'no'\n",
    "\n",
    "    if output_content == ans.split('.')[0].strip():\n",
    "         correct_cnt = correct_cnt + 1\n",
    "    else:\n",
    "        #print(code)\n",
    "        print(output_content,ans)\n",
    "        # print(code)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "1696\n"
     ]
    }
   ],
   "source": [
    "print(error_cnt)\n",
    "print(correct_cnt)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.9113379903277807\n"
     ]
    }
   ],
   "source": [
    "print(correct_cnt/len(datas))\n",
    "#max tokens是"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1,3,5,2,4\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "output_content = \"[1,3,5,2,4]\"\n",
    "pattern = r\"[\\{\\[]([^}\\]]*)[\\}\\]]\"\n",
    "match1 = re.search(pattern, output_content)\n",
    "\n",
    "\n",
    "if match1:\n",
    "    content_output = match1.group(1)\n",
    "    \n",
    "print(content_output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0, 1, 2, 3, 4, 10, 7\n",
      "[0, 1, 2, 3, 4, 7, 10]\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "\n",
    "text = \"{0, 1, 2, 3, 4, 10, 7}\"\n",
    "pattern = r\"[\\{\\[]([^}\\]]*)[\\}\\]]\"\n",
    "match = re.search(pattern, text)\n",
    "\n",
    "if match:\n",
    "    content = match.group(1)\n",
    "    print(content)  # 输出: 0, 1, 2, 3, 4, 6, 7\n",
    "    numbers = list(map(int, content.split(',')))\n",
    "    numbers.sort()\n",
    "    print(numbers)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
